services:
    football-teams-creator:
        build: .
        container_name: football-teams-creator
        restart: unless-stopped

        ports:
            - "${PORT}:${PORT}"

        environment:
            PORT: ${PORT}
            SQLITE_DATABASE_PATH: ${SQLITE_DATABASE_PATH}
            TEAMS_DATA_PATH: ${TEAMS_DATA_PATH}
            APP_TITLE: ${APP_TITLE}

        volumes:
            - ./data:/app/data
